name: Output Repository Contents

on: 
  pull_request_target:
  workflow_dispatch:
  

jobs:
  output_contents:
    name: Output Repository Contents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List repository contents
        run: |
          echo "Repository Contents:"
          ls -R
